apiVersion: v1
kind: Service
metadata:
  name: cardinal-registry
  namespace: registry
  labels:
    app: cardinal-repository-k8s
spec:
  selector:
    app: cardinal-repository-k8s
  ports:
  - port: 5000
    targetPort: 5000
  externalTrafficPolicy: Local
  type: LoadBalancer
